"""baseline esquema fase 6

Revision ID: 012cc52a2771
Revises: 
Create Date: 2026-07-22 22:57:20.013731
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '012cc52a2771'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('es_multivalor', sa.Boolean(), nullable=False),
    sa.Column('detectable_automaticamente', sa.Boolean(), nullable=False),
    sa.Column('nivel_sugerido', sa.String(length=10), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('imagen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash_contenido', sa.String(length=64), nullable=False),
    sa.Column('hash_perceptual', sa.String(length=32), nullable=True),
    sa.Column('ancho', sa.Integer(), nullable=True),
    sa.Column('alto', sa.Integer(), nullable=True),
    sa.Column('formato', sa.String(length=10), nullable=True),
    sa.Column('tamano_bytes', sa.BigInteger(), nullable=True),
    sa.Column('fecha_indexado', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('estado_analisis', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash_contenido')
    )
    op.create_table('modelo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('raiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('ruta_montaje', sa.String(length=500), nullable=False),
    sa.Column('ultima_verificacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('alias_modelo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analisis_pose',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imagen_id', sa.Integer(), nullable=False),
    sa.Column('version_modelo', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('num_figuras', sa.Integer(), nullable=False),
    sa.Column('figura_principal', sa.Integer(), nullable=True),
    sa.Column('pose_detectada', sa.Boolean(), nullable=False),
    sa.Column('motivo', sa.String(length=50), nullable=True),
    sa.Column('landmarks_2d', sa.JSON(), nullable=True),
    sa.Column('world_landmarks_3d', sa.JSON(), nullable=True),
    sa.Column('visibilidad_zonas', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['imagen_id'], ['imagen.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imagen_id')
    )
    op.create_table('carpeta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raiz_id', sa.Integer(), nullable=False),
    sa.Column('ruta_relativa', sa.String(length=500), nullable=False),
    sa.Column('carpeta_padre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carpeta_padre_id'], ['carpeta.id'], ),
    sa.ForeignKeyConstraint(['raiz_id'], ['raiz.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raiz_id', 'ruta_relativa')
    )
    op.create_table('cola_revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imagen_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=12), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['imagen_id'], ['imagen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coleccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('imagen_portada_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['imagen_portada_id'], ['imagen.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('imagen_modelo',
    sa.Column('imagen_id', sa.Integer(), nullable=False),
    sa.Column('modelo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['imagen_id'], ['imagen.id'], ),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelo.id'], ),
    sa.PrimaryKeyConstraint('imagen_id', 'modelo_id')
    )
    op.create_table('medidas_pose',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imagen_id', sa.Integer(), nullable=False),
    sa.Column('version_reglas', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('torso_fiable', sa.Boolean(), nullable=False),
    sa.Column('es_primer_plano', sa.Boolean(), nullable=False),
    sa.Column('angulos', sa.JSON(), nullable=True),
    sa.Column('senales', sa.JSON(), nullable=True),
    sa.Column('escorzo', sa.JSON(), nullable=True),
    sa.Column('orientacion', sa.JSON(), nullable=True),
    sa.Column('extension', sa.Float(), nullable=True),
    sa.Column('compacidad', sa.Float(), nullable=True),
    sa.Column('dispersion_vertical', sa.Float(), nullable=True),
    sa.Column('dispersion_horizontal', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['imagen_id'], ['imagen.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imagen_id')
    )
    op.create_table('miniatura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imagen_id', sa.Integer(), nullable=False),
    sa.Column('ruta', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['imagen_id'], ['imagen.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imagen_id')
    )
    op.create_table('opcion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('id_padre', sa.Integer(), nullable=True),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['id_padre'], ['opcion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categoria_id', 'codigo')
    )
    op.create_table('carpeta_opcion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carpeta_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('opcion_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['carpeta_id'], ['carpeta.id'], ),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['opcion_id'], ['opcion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carpeta_id', 'opcion_id')
    )
    op.create_table('imagen_coleccion',
    sa.Column('imagen_id', sa.Integer(), nullable=False),
    sa.Column('coleccion_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('fecha_agregado', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coleccion_id'], ['coleccion.id'], ),
    sa.ForeignKeyConstraint(['imagen_id'], ['imagen.id'], ),
    sa.PrimaryKeyConstraint('imagen_id', 'coleccion_id')
    )
    op.create_table('imagen_opcion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imagen_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('opcion_id', sa.Integer(), nullable=False),
    sa.Column('origen', sa.String(length=12), nullable=False),
    sa.Column('confianza', sa.Float(), nullable=True),
    sa.Column('version_reglas', sa.String(length=20), nullable=True),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['imagen_id'], ['imagen.id'], ),
    sa.ForeignKeyConstraint(['opcion_id'], ['opcion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modelo_opcion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('opcion_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelo.id'], ),
    sa.ForeignKeyConstraint(['opcion_id'], ['opcion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('modelo_id', 'opcion_id')
    )
    op.create_table('ubicacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imagen_id', sa.Integer(), nullable=False),
    sa.Column('raiz_id', sa.Integer(), nullable=False),
    sa.Column('carpeta_id', sa.Integer(), nullable=True),
    sa.Column('ruta_relativa', sa.String(length=500), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=10), nullable=False),
    sa.Column('ultima_verificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['carpeta_id'], ['carpeta.id'], ),
    sa.ForeignKeyConstraint(['imagen_id'], ['imagen.id'], ),
    sa.ForeignKeyConstraint(['raiz_id'], ['raiz.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raiz_id', 'ruta_relativa')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ubicacion')
    op.drop_table('modelo_opcion')
    op.drop_table('imagen_opcion')
    op.drop_table('imagen_coleccion')
    op.drop_table('carpeta_opcion')
    op.drop_table('opcion')
    op.drop_table('miniatura')
    op.drop_table('medidas_pose')
    op.drop_table('imagen_modelo')
    op.drop_table('coleccion')
    op.drop_table('cola_revision')
    op.drop_table('carpeta')
    op.drop_table('analisis_pose')
    op.drop_table('alias_modelo')
    op.drop_table('raiz')
    op.drop_table('modelo')
    op.drop_table('imagen')
    op.drop_table('categoria')
    # ### end Alembic commands ###
