"""vector_pose fase 7

Revision ID: 8f7c57a47a5a
Revises: 012cc52a2771
Create Date: 2026-07-22 23:53:48.209302
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import backend.db.tipos  # tipo Vector (pgvector) usado en las columnas


# revision identifiers, used by Alembic.
revision: str = '8f7c57a47a5a'
down_revision: Union[str, None] = '012cc52a2771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vector_pose',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imagen_id', sa.Integer(), nullable=False),
    sa.Column('vector', backend.db.tipos.Vector(), nullable=False),
    sa.Column('vector_reflejado', backend.db.tipos.Vector(), nullable=False),
    sa.Column('mascara', sa.JSON(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['imagen_id'], ['imagen.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imagen_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vector_pose')
    # ### end Alembic commands ###
