"""excluir imagen

Revision ID: e4cd1ce3be7d
Revises: 8f7c57a47a5a
Create Date: 2026-07-23 20:52:11.446559
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import backend.db.tipos  # tipo Vector (pgvector) usado en las columnas


# revision identifiers, used by Alembic.
revision: str = 'e4cd1ce3be7d'
down_revision: Union[str, None] = '8f7c57a47a5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imagen', sa.Column('excluida', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imagen', 'excluida')
    # ### end Alembic commands ###
